### PR TITLE
Adding tests for coalesce.

### PR DESCRIPTION
**Pull request by msdemlei**
Unrelatedly, porting the two pieces of python to python3, and adding
uuids to additionaltests; that's just to let me run the tests.

This is related to https://github.com/ivoa-std/ADQL/pull/69

### CODE REVIEW

**Review by Zarquan — APPROVED** [review]
I like the idea of adding a UUID.

**Comment by Zarquan** [comment]
Putting 3 separate things in one commit is a bit messy.

**Comment by Zarquan** [comment]
If you are going to add branches to this repo rather than create your own fork, can you prefix the branch name with your user name. e.g. `msdemlei-add-coalesce`

**Comment by msdemlei** [comment]
On Fri, Dec 10, 2021 at 06:54:11AM -0800, Zarquan wrote:
> If you are going to add branches to this repo rather than create
> your own fork, can you prefix the branch name with your user name.
> e.g. `msdemlei-add-coalesce`

Dumb question: what's the purpose of adding a name?  I mean, there
are only so many characters in a manageable branch name, and I think
we should have good reasons to spend quite a few of them on an
information that I think (a) doesn't matter much in most cases and
(b) can easily found out using git log.

On the other hand, I'm of course all for discouraging
"fix-a-few-bugs" and "add-to-features", but I don't think policies
help a lot there.

**Pull request merged**
