### PR TITLE
Adql validator

### PR DESCRIPTION
**Pull request by gmantele**
This PullRequest adds a lot of ADQL queries into the `src/adql/ivoa/` directory. All of them are supposed to be generic. They should pass the syntactic parsing of any ADQL service (e.g. TAP service). No running service or database is required to validate them.

**About the test files**

I tried to gather as many different queries as possible in order to cover most of the common and un-common ADQL queries. Being a simple human, I probably forgot some queries, but this should already constitute a good basis.

All test queries are gathered into several files. Each file more or less represents a section of the ADQL-2.1 document. When prefixed by `O` and a number, the file tests an optional feature. When prefixed by `X` and a number, the file gathers queries provided by an external source and proposing interesting (complex) ADQL queries. See `src/adql/ivoa/README.md` for more details about this file organisation.

Some of the queries added here are coming from the `.../gavo/` and `.../roe/` directories. So, thanks to their authors (resp. Markus and Dave).

Also, thank you to Alberto for his contribution to the `src/adql/ivoa/X1_obscore_eso.xml`.

**About the validator**

The ADQL validator has been updated (mainly to support set operators) and fixed (on several aspects). The GitHub CI named `ADQL Validation` (see [validate-queries.yml](https://github.com/ivoa/lyonetia/blob/master/.github/workflows/validate-queries.yml)) is run each time commits are pushed on the `master` branch. _Now, it only validates the ADQL queries inside the `src/adql/ivoa/` folder (and no longer the `.../gavo/` and `.../roe/` folders)._

Some queries do not pass the validation, and this is normal. I want to discuss about them before either removing them from the validation tests set or fixing the validator itself.

### CODE REVIEW

**Comment by gmantele** [comment]
Looking at the CI which fails, it seems a GitHub Action is not allowed to submit a Wiki page:

> remote: Permission to ivoa/lyonetia.wiki.git denied to github-actions[bot].
> fatal: unable to access 'https://github.com/ivoa/lyonetia.wiki.git/': The requested URL returned error: 403

This is weird as I was able to do so on my fork of this repository. If anyone has an idea how I could fix this, it would be very useful. The wiki this CI workflow tries to write is the validation report saying which ADQL queries did not pass and why.

**Comment by gmantele** [comment]
Hi Markus,

Thank you for your feedback. I agree for most of your comments. Actually, the queries you pointed out are the one I wanted to discuss.

Maybe I should have given the URL toward the validation reports for all these queries: <https://github.com/gmantele/lyonetia/wiki/PR%232>. Note that this report comes from my own fork, as I still have this CI issue to publish this report on ivoa/lyonetia (see above). Anyway, in this report, you can see all queries that do not pass my parser either and that I consider as queries to drop or review.

Below is my answers to all the points you already made.

About `ivoa/0_whitespace.xml`, as you can see in the header, I mostly copy/paste what Jon suggested, but I disagree with some of them. I left these queries here just to start a discussion and decide with everyone if we should consider them as legal or not.

NOTE: I just realized that the file from you and Jon I used to build these one are now different. I probably updated them while I was preparing this PullRequest (which I did during several months). I will find time to update my examples with the updated version of your files.

----

> ivoa/0_whitespace.xml#118c7d86-4509-11e6-b60c-9d2c33f9b7a2
> 
> DaCHS rejects that because it doesn't like 3 as a
> geometry_value_expression.  I haven't gone down the rules to make sure
> there's no way this could become legal, but clearly this query would
> fail anyway.  I think what's exercised here would be exercised quite as
> well by writing "u" rather than "3" without setting traps for basically
> sane parsers.

I completely agree with you. `CENTROID(...)` must apply on a geometry. Anything else should be rejected.

----

> ivoa/0_whitespace.xml#1aa0786e-4509-11e6-b60c-9d2c33f9b7a2
> 
> That's I think grammatically ok.  We're generally cavalier about
> whitespace in our grammar, but I see not a shroud of evidence that SQL
> or someone else wouldn't allow whitespace around the * in a count.  I'd
> say we ought to drop the example.

Again, I completely agree. This successfully pass my parser too and I don't see any reason why it wouldn't be legal.

----

> ivoa/0_whitespace.xml#e48c4834-450d-11e6-b20b-6d529bdffd4c
> 
> I propose replacing 'junk' by 'ICRS'; DaCHS' grammar already filters out
> bad reference frames (that would fail down the road), and I don't
> think lyonetia should work against that implementation decision (and we
> want to drop the frames anyway).

and 

> ivoa/O1_geometrical_functions.xml#898cf934-450c-11e6-8564-332de33a5c03
> 
> Again, I'd drop that now.  I don't think any more that we should keep
> engines from throwing out bad coordinate systems at parse time (and
> since we want to get rid of the systems anyway, I don't think there's
> a major reason to exercise them too much).

I agree too. My parser is also able to raise error when an incorrect coordinate system is given. I just disable this verification here because I did not know if it was my own interpretation of the ADQL-2.0 standard or not. Interesting think, ADQL-2.1, does not specify whatsoever what standard should be used for this COORDSYS argument. But as you said, not really important when we know it is now deprecated.

Anyway, I can easily enable the verification of coordsys in this validator and so, such error would immediately be raised. Just waiting for a confirmation and I do it.

----

> ivoa/1_select.xml#fe956f66-3c3e-410d-baa4-59305da8ddfc
> 
> DaCHS, as a little extension, actually accepts names starting with an
> underscore, and with postgres, that's very convenient.  While I'm all
> for exercising the name parser, perhaps we can use a name broken in some
> other way, just because leading-underscore names are such an obvious
> extension people may want to have?  Perhaps .somename?  I give you that
> may exercise different rules.

This time, I agree and I do not agree with you. I explain. I personally agree that in DBMS (like Postgres) this is not an issue. So, in ADQL, I would personally allow column names prefixed with an underscore.

However, since ADQL-2.0, a column name **must** start with an alphabetic letter, according to the BNF. This is still the case in ADQL-2.1:

```
<column_name> ::= <identifier>

<identifier> ::= <regular_identifier> | <delimited_identifier>

<regular_identifier> ::=
                         <simple_Latin_letter>...
                         [ { <digit> | <simple_Latin_letter> | <underscore> }... ]
```

The same rule applies to a UDF name.

Whether or not I personally disagree with this, we should NOT allow our validator to ignore some part of the ADQL standard. Otherwise, we could not call it a "validator".

So, two solutions here:

1. We now allow column names and UDF to start with an underscore. ADQL-2.1 should then be updated.
2. We don't change anything. So, we keep the ADQL BNF as it is currently and we keep this validation query (ivoa/1_select.xml#fe956f66-3c3e-410d-baa4-59305da8ddfc).

What do you think?

----

> ivoa/1_select.xml#85e497ac-4403-4f84-8aa0-a3ee3da514cc
> 
> Regrettably, that's valid SQL (and ADQL).  What's there is an ugly short
> form of SELECT 2 AS weird FROM stars.

Should it be really valid in ADQL? If it does, it could lead to unexpected behavior from what expect our users. I agree that it is a good thing to follow as closely as possible SQL, but should we strictly follow it when it is obviously not desired? I would personally save our users sanity by strictly forbidding regular column names prefixed by a digit. A regular ADQL user expects a column name prefixed by a digit, and since this is forbidden in ADQL, he will get an error ; this is, according to me, better than allowing an implicit column name alias.

This "issue" actually comes from the fact that the BNF does not specify how grammar tokens should be identified and how space characters should be considered. This is one of the reasons why we want to move to a PEG grammar. So the question is: do we want to allow such dangerous syntax when we will have a PEG grammar? If yes, how would you write that in PEG syntax? (I don't think it will be easy)

On the implementation side, I don't think I can easily change the parsing mechanism of my parser to allow such ugly thing ; it could be possible, but the trick will be as ugly as this syntax.

----

> ivoa/O1_geometrical_functions.xml#052cd50e-4509-11e6-b60c-9d2c33f9b7a2
> 
> That's legal by now for all I can tell.  Let's drop it (or declare it as
> valid="True").

and

> ivoa/O1_geometrical_functions.xml#dfd90750-450d-11e6-b20b-6d529bdffd4c
> 
> That's now legal for all I can tell.

Completely agree and I did not know why you kept these queries in your validation set. That's where I took them. But now that I check your files, it seems you fixed them. So, I can now do the same here :-D (I just kept them to not forget to discuss about them).

----

> ivoa/O1_geometrical_functions.xml#1655f288-4d02-11e6-8c9d-819288b39233
> 
> String literals in SQL cannot be broken across input lines.  For this to
> be valid, you have to join the argument of the first REGION.

You are right. I'll fix it. I don't even know why this passed.

**Comment by msdemlei** [comment]
On Tue, Jan 24, 2023 at 02:25:25AM -0800, Grégory Mantelet wrote:
> > ivoa/1_select.xml#fe956f66-3c3e-410d-baa4-59305da8ddfc
> > 
> However, since ADQL-2.0, a column name **must** start with an
> alphabetic letter, according to the BNF. This is still the case in
> ADQL-2.1:

Absolutely.  And I don't think we should change that, as that may
make implementation a lot harder on top of RDMSes that are less
forgiving than postgres.

> Whether or not I personally disagree with this, we should NOT allow
> our validator to ignore some part of the ADQL standard. Otherwise,
> we could not call it a "validator".

Well... we have some leeway as to what tests we run and what we don't
test against.  For instance, DaCHS extends ADQL with TABLESAMPLE.  We
*could* include a test that an implementation rejects something like

  SELECT * from foo TABLESAMPLE(0.1)

which clearly is invalid ADQL 2.1 -- but we don't, as I'd argue we
don't want to be in people's ways when they prototype features for
the next versions of ADQL.

Similarly, in this case we *could* say identifiers with leading
underscores may be a reasonable extension and we simply don't test
whether or not an implementation rejects identifiers with leading
underscores.

By my criteria what to validate and what not to validate,
<https://blog.g-vo.org/requirements-and-validators.html>, I don't see
a compelling argument why we should make sure parsing fails in this
case.  But I certainly might be missing something.

> So, two solutions here:
> 
> 1. We now allow column names and UDF to start with an underscore. ADQL-2.1 should then be updated.
> 2. We don't change anything. So, we keep the ADQL BNF as it is currently and we keep this validation query (ivoa/1_select.xml#fe956f66-3c3e-410d-baa4-59305da8ddfc).
> 
> What do you think?

If my reasoning above is about right, I'd say we can just drop the
test and not exercise the whole thing.

But then if you want to keep the test, I won't complain (and just
think about an ignore pattern in my test suite).


> > ivoa/1_select.xml#85e497ac-4403-4f84-8aa0-a3ee3da514cc
> > 
> > Regrettably, that's valid SQL (and ADQL).  What's there is an ugly short
> > form of SELECT 2 AS weird FROM stars.
> 
> Should it be really valid in ADQL? If it does, it could lead to
> unexpected behavior from what expect our users. I agree that it is

True -- it sure surprised me, and I had to hack quite a bit to make
DaCHS' parser accept abominations like these.

> This "issue" actually comes from the fact that the BNF does not
> specify how grammar tokens should be identified and how space
> characters should be considered. This is one of the reasons why we
> want to move to a PEG grammar. So the question is: do we want to
> allow such dangerous syntax when we will have a PEG grammar? If
> yes, how would you write that in PEG syntax? (I don't think it will
> be easy)

Ok... interesting.  I was just staring a bit at section 5.2 of SQL92
trying to figure out SQL's tokenisation rules, since so far I was
pretty sure SQL engines are required to parse 2foo as 2 AS foo (and
frankly, I deplore that the AS is optional quite a bit as well).
Interestingly, this doesn't seem to have much factual basis.

And SQL92 in 5.2 says:

  Any <token> may be followed by a <separator>. A <nondelimiter
  token> shall be followed by a <delimiter token> or a <separa-
  tor>. If the Format does not allow a <nondelimiter token> to be
  followed by a <delimiter token>, then that <nondelimiter token>
  shall be followed by a <separator>.

And both <regular identifier> and <unsigned numeric literal> are
<nondelimiter tokens>-s.  I *think* the cited language forbids two
nondelimiting tokens next to each other.  Empirically, Postgres
understands 2foo, but sqlite3 doesn't.  That made me try the SQL
Fiddle.  MySQL doesn't, Oracle does, SQLServer is currently broken
there.

So... yeah, let's consider it outlawed.  People devious enough to
write such a thing deserve no better, and they won't have much fun
when they directly talk to SQL engines anyway.

**Comment by msdemlei** [comment]
On Thu, Jan 26, 2023 at 02:08:33PM +0100, msdemlei wrote:
["2foo"]
> So... yeah, let's consider it outlawed.  People devious enough to
> write such a thing deserve no better, and they won't have much fun
> when they directly talk to SQL engines anyway.

Well, it turns out it's not quite as simple.  Looking at my grammar
(and I don't think this will be much different for some other PEG
grammar), it actually seems to be quite involved to disallow 2foo and
at the same time accept (2)foo. 

The straighforward way to write the rules would be something like

  <asClause> ::= (AS|<whitespace>) <alias>
  <derivedColumn> ::= <expr> [<asClause>]

but that outlaws the (2)foo, which I'd rather not.   Having
different rules depending on whether <expr> ends with a
<nondelimiting token> is equally unattractive. 

Perhaps I start liking 2foo after all.  Or we require the AS, which
would immediately solve the whole problem (but would probably break
many queries that are out there).

**Comment by msdemlei** [comment]
On Tue, Jan 24, 2023 at 02:25:25AM -0800, Grégory Mantelet wrote:
> Thank you for your feedback. I agree for most of your comments.
> Actually, the queries you pointed out are the one I wanted to
> discuss.

After your last push, there's still 
O1_geometrical_functions.xml#898cf934-450c-11e6-8564-332de33a5c03
that has a bad reference frame -- was that an oversight?

I have then looked a bit at X1_obscore_eso.xml.  I'm failing all of
7928f365-6631-4415-be7d-29865f14c083,
7f30606b-509a-491f-8b5a-5d712f37670c,
4b8bd9f4-611c-4d2e-8227-2525dee664d2,
084e068-8f31-4007-9d89-115dec609452,
6794498f-1603-4a12-b0dd-e48be1acab4b in there because they are using
eso_-prefixed UDFs. For all I can tell, rejecting UDFs with a foreign
prefix is standards-compliant (and indeed mandatory) behaviour.

Now, I'm all for exercising UDF parsing, but I think we will then
have to do one of two things: either we parameterise the prefix used
in some way.  Or we we let examples declare which UDFs they require
so validators can skip them when their target systems do not support
the UDFs in question.

**Comment by gmantele** [comment]
> After your last push, there's still
> O1_geometrical_functions.xml#898cf934-450c-11e6-8564-332de33a5c03
> that has a bad reference frame -- was that an oversight?

Oups, I forgot this one. Thanks for having checked.

----

> I have then looked a bit at X1_obscore_eso.xml.  I'm failing all of
> 7928f365-6631-4415-be7d-29865f14c083,
> 7f30606b-509a-491f-8b5a-5d712f37670c,
> 4b8bd9f4-611c-4d2e-8227-2525dee664d2,
> 084e068-8f31-4007-9d89-115dec609452,
> 6794498f-1603-4a12-b0dd-e48be1acab4b in there because they are using
> eso_-prefixed UDFs. For all I can tell, rejecting UDFs with a foreign
> prefix is standards-compliant (and indeed mandatory) behaviour.

Those do not fail in my validator as any unknown function is considered as a UDF. But in an actual TAP service, I would require a UDF declaration for all of them.

Then about rejecting UDFs based on the prefix, I don't think it is a good idea in the context of this ADQL language validator. And I don't think it was the meaning of the ADQL standard either:

_Sec. 4.3.1_
> In order to avoid name conflicts, user defined function names SHOULD
> include a prefix which indicates the name of the institute or project which
> created the function.

and _Appendix A_

> <user_defined_function> ::=
>     <user_defined_function_name> <left_paren>
>     ....
> <user_defined_function_name> ::=
>     [ <default_function_prefix> ] <regular_identifier>

My understanding is that a UDF is really a custom function set up on the service. It is then up to the service to decide whether or not a prefix and which one should be used. Again, the usage of prefix is a strong recommendation (SHOULD) but is not mandatory. So, I don't think that the language validator must reject UDFs based on their prefix. But of course, if you want to do it in your implementation, it is fine, you're right to do so.

However...

> Now, I'm all for exercising UDF parsing, but I think we will then
> have to do one of two things: either we parameterise the prefix used
> in some way.  Or we we let examples declare which UDFs they require
> so validators can skip them when their target systems do not support
> the UDFs in question.

...that could be a good idea. We can indeed declare UDFs in the validation test file, using the same syntax than in TAPRegExt. This seems a very good alternative and it is better than skipping any unknown function as I do currently.

I'll try to implement that in this validator very soon.

**Comment by gmantele** [comment]
Anyway, have you also checked the following queries in `0_whitespace.xml` (which is now a copy of your `whitespace.xml`):

- d4c3a72c-4458-11e6-96e2-28b2bdcff70b
- dbef92f4-4458-11e6-96e2-28b2bdcff70b
- 1f5d27dc-450c-11e6-8564-332de33a5c03

All failing because of a missing JOIN condition. It seems they pass in your case ; I assume you have set an implicit `NATURAL JOIN`.

**Comment by gmantele** [comment]
Also:

- ccd99070-4508-11e6-b60c-9d2c33f9b7a2
- b8bca746-4cfe-11e6-b1bc-3d3af74034fa

fail because of the `NULL` coord. sys. argument. `NULL` is a reserved keyword in ADQL, but is never used anywhere in the (BNF) grammar, except for `IS [NOT] NULL`. Though I agree this would make sense to allow `NULL` wherever a value can be written, but strictly speaking, ADQL does not specify that.

Should we fix the ADQL grammar like below?

```
<value_expression> ::=
      NULL
    | <numeric_value_expression>
    | <string_value_expression>
    | <geometry_value_expression>
```

Which, by the way, would avoid having to include `NULL` as possible 1st parameter of `CAST`, as written in the ADQL grammar:

```
CAST <left_paren> ( <value_expression> | NULL ) AS <cast_target> <right_paren>
```

Should we do the same in ADQL-2.0, with an Erratum?

**Comment by msdemlei** [comment]
On Fri, Jan 27, 2023 at 05:27:50AM -0800, Grégory Mantelet wrote:
> - d4c3a72c-4458-11e6-96e2-28b2bdcff70b
> - dbef92f4-4458-11e6-96e2-28b2bdcff70b
> - 1f5d27dc-450c-11e6-8564-332de33a5c03
>
> All failing because of a missing JOIN condition. It seems they pass
> in your case ; I assume you have set an implicit `NATURAL JOIN`.

Uh, ouch, you're right that these shouldn't pass, and I shouldn't
have dragged them from my unit tests (where they were used for
something completely different anyway).  But unfortunately no, it's
not been wisdom (like default NATURAL).  It's been a far too
permissive grammar, where I have taken a shortcut ages ago that I
shouldn't have taken.

Feel free to drop these, add join conditions, or do valid="False".

**Comment by msdemlei** [comment]
On Fri, Jan 27, 2023 at 05:39:45AM -0800, Grégory Mantelet wrote:
> <value_expression> ::=
>       NULL
>     | <numeric_value_expression>
>     | <string_value_expression>
>     | <geometry_value_expression>

DaCHS has had the NULL as an alternative in the
value_expression_primary nonterminal.  Briefly skimming the grammar,
it would seem that's about equivalent to having it in value_expression
itself.

> Should we do the same in ADQL-2.0, with an Erratum?

I'd certainly argue in favour of that.

**Comment by msdemlei** [comment]
On Fri, Jan 27, 2023 at 04:48:22PM +0100, msdemlei wrote:
> something completely different anyway).  But unfortunately no, it's
> not been wisdom (like default NATURAL).  It's been a far too
> permissive grammar, where I have taken a shortcut ages ago that I

Well... Now that I consult the ADQL grammar... Ok, so I wasn't overly
permissive at all, and although it looked like a shortcut at first I
actually just implemented what the grammar says:

  <qualified_join> ::=
    <table_reference> [ NATURAL ] [ <join_type> ] JOIN
    <table_reference> [ <join_specification> ]

So, <join_specification> happens to be optional regardless of whether
or not there is a NATURAL *in our grammar*.

Since a non-NATURAL, non-specification JOIN will later fail in the
backend database, one might argue we shouldn't let it pass in ADQL
either.  This would mean we'd have to write something like

  <qualified_join> ::=
    <table_reference> <natural_join>
    | <table_reference> <non_natural_join>

  <natural_join> ::=  NATURAL [ <join_type> ] JOIN <table_reference>

  <non_natural_join> ::=  [ <join_type> ]
    JOIN <table_reference> <join_specification>

(disclaimer: not tested).

I'd be mildly in favour of that, enough that I'd implement it but not
enough that I'd push it into the spec myself.

Meanwhile, for the tests I think we ought to just put NATURAL in
front of all the JOIN-s (though it's questionable whether these should
be in whitespace...).  That way, we don't have to invent column names
and conditions on them.

**Comment by gmantele** [comment]
> Feel free to drop these, add join conditions, or do valid="False".

I drop these from `0_whitespace.xml` and I moved one to a new file `2_from.xml` in which I added several tests on the usage of FROM and all JOINs. It might not be exhaustive yet.

----

> DaCHS has had the NULL as an alternative in the
> value_expression_primary nonterminal.  Briefly skimming the grammar,
> it would seem that's about equivalent to having it in value_expression
> itself.

> >  Should we do the same in ADQL-2.0, with an Erratum?

> I'd certainly argue in favour of that.

OK. So, I added that in my TeX file for ADQL and I will push it next week on GitHub.
I'll see also next week for an ADQL-2.0 Erratum.

----

> Since a non-NATURAL, non-specification JOIN will later fail in the
> backend database, one might argue we shouldn't let it pass in ADQL
> either.  This would mean we'd have to write something like
> 
>   <qualified_join> ::=
>     <table_reference> <natural_join>
>     | <table_reference> <non_natural_join>
> 
>   <natural_join> ::=  NATURAL [ <join_type> ] JOIN <table_reference>
> 
>   <non_natural_join> ::=  [ <join_type> ]
>     JOIN <table_reference> <join_specification>
> 
> (disclaimer: not tested).

It seems pretty ok to me. I'll fix that in the BNF next week too, and then I'll try to see if the BNF will still be consistent.

> I'd be mildly in favour of that, enough that I'd implement it but not
> enough that I'd push it into the spec myself.

I don't see what makes you hesitate. Actually, it really looks like a fix of the grammar that everyone already applied in their implementation. So, actually, this should be again, another Erratum to ADQL-2.0, isn't it?

> Meanwhile, for the tests I think we ought to just put NATURAL in
> front of all the JOIN-s (though it's questionable whether these should
> be in whitespace...).  That way, we don't have to invent column names
> and conditions on them.

You're right that when running so many queries in a real service, it is more convenient to have a well defined set of tables and columns and use NATURAL JOINs as much as possible. However, the goal of this ADQL validator is to just validate the official grammar, and not how well existing parsers or ADQL services can deal with the execution of the query. That's why, my validator is offline and does not check whether table and column names exist on a database...there is no database. So, with or without NATURAL, the validator should not complain about column and table name not existing in a database. Taking that into account, I don't think I like to alter the diversity of the test queries by forcing the usage of NATURAL JOINs everywhere. More different simple and complex queries we have, better the tests will be.

**Comment by msdemlei** [comment]
On Fri, Jan 27, 2023 at 09:51:08AM -0800, Grégory Mantelet wrote:
> > I'd be mildly in favour of that, enough that I'd implement it but not
> > enough that I'd push it into the spec myself.
>
> I don't see what makes you hesitate. Actually, it really looks like
> a fix of the grammar that everyone already applied in their
> implementation. So, actually, this should be again, another Erratum
> to ADQL-2.0, isn't it?

I hesitate because we're deviating from the SQL92 grammar here.  It
has, as ADQL 2.0 has:

   <qualified join> ::=
         <table reference> [ NATURAL ] [ <join type> ] JOIN
           <table reference> [ <join specification> ]

I don't have time to dig into the spec to where it says "have either
NATURAL or a <join specification>" -- or to ascertain that it doesn't
say that and then figure out under what circumstances a single JOIN
might be legal after all (perhaps as an alias for ","?).

But I am saying that if we deviate from SQL92, we should be sure we
know what we're doing, and I'm hesitating because this is not enough
of a big deal for me to really start thinking hard.  But as I said,
if someone else does the deep thinking, I think I'm fine with the
change per se.

A 2.0 Erratum I think would be overdoing it, though.  I don't think
there's operational harm the way it is; bad queries just fail a bit
later, that's all.

**Comment by msdemlei** [comment]
I have another qualm, this time with
2104c723-4ea8-42d7-bf96-7735cc9fd88b in O7_conditional...

This is designed to throw out COALESCE(NULL); but the current grammar
doesn't forbid that (any more, given we're allowing NULL as
value_expression, and before that it just outlawed it because it
outlawed NULL everywhere).

Now, I somewhat follow your reasoning that the expression semantically
is not very sensible, but that's not a grammar thing.  If there's a
grammar aspect to this, it would perhaps be more about having just one
argument (which isn't very sensible either).  But again, the grammar
explicitly allows that.  In that it is following SQL92, which has

        <case abbreviation> ::=
        999(whatever)
              | COALESCE <left paren> <value expression>
                      { <comma> <value expression> }... <right paren>

So... I'd say this should either be valid or dropped.

**Comment by gmantele** [comment]
> I have another qualm, this time with
> 2104c723-4ea8-42d7-bf96-7735cc9fd88b in O7_conditional...
> 
> This is designed to throw out COALESCE(NULL); but the current grammar
> doesn't forbid that (any more, given we're allowing NULL as
> value_expression, and before that it just outlawed it because it
> outlawed NULL everywhere).

You're perfectly right. My mistake. I just fixed the validator and updated this test. Now this query should successfully pass.

In addition, I've updated my parser (and so the validator) to allow `NULL` values anywhere a value can be....it was not yet the case.

**Comment by gmantele** [comment]
I pushed all modifications we spoke about together in the last DAL Running Meeting (meeting#15, on the 10th March 2023 ; see [DAL Twiki](https://wiki.ivoa.net/twiki/bin/view/IVOA/IvoaDAL_RunningMeetings#15) for notes).

@msdemlei , as you can see in this commit - https://github.com/ivoa/lyonetia/pull/16/commits/dd2bfaaf4b955c3880c03da83a48cbb9cc028af8 - I have modified the `X1_obscore_eso.xml` file so that UDFs are declared in each query test instead of globally in the test set, as we agreed during the running meeting. I hope it is ok like this for you.

Anyway, as you can all see, one of the two CI checks that I set up failed. It did because it is not allowed to publish the validation report in the IVOA/lyonetia wiki, and not because the validation tests did not pass. I hope it will succeed once we will merge this PullRequest within the master branch. In the meantime, you can see the validation report in the repo I am pushing this Pull Request from: https://github.com/gmantele/lyonetia/wiki/PR%232

According to this report, all tests now pass the ADQL validator based on VOLLT (which is in the `src/adql-validator/` directory ; this validator is the one used to publish the report mentioned above).

Is it also ok for your validator based on DACHS, @msdemlei ?

If yes, and unless there is new opposition, I think we can merge this PullRequest. _I'll wait one or two days for comments, approvals or so, before merging it._

**Comment by msdemlei** [comment]
On Wed, Mar 15, 2023 at 04:17:02AM -0700, Grégory Mantelet wrote:
> @msdemlei , as you can see in this commit -
> https://github.com/ivoa/lyonetia/pull/16/commits/dd2bfaaf4b955c3880c03da83a48cbb9cc028af8
> - I have modified the `X1_obscore_eso.xml` file so that UDFs are
> declared in each query test instead of globally in the test set, as
> we agreed during the running meeting. I hope it is ok like this for
> you.

I like it, and that should work for me to either skip these tests or
perhaps rig DaCHS to accept these UDFs.

> Is it also ok for your validator based on DACHS, @msdemlei ?

I'll make it pass, just not right now (busy elsewhere).

Please go ahead and merge as you see fit.  Thanks!

**Comment by gmantele** [comment]
Indeed, after the merge, the validation report was successfully pushed in the wiki.

In 16a2f33aeb614cb30f23491047705825c3d2c2fd I just updated the badges in the `README.md` file to reflect the validation status and give the link (when clicking on the badge) to the list of validation reports.

**Pull request merged**
