### PR TITLE
Add ADQL validation

### PR DESCRIPTION
**Pull request by gmantele**
This Pull Request proposes an ADQL validator based on the Java library [VOLLT](https://github.com/gmantele/vollt)/TAP-Lib (currently on its branch `adql2.1`).

This validator runs in command line. It takes several files/directories in argument. Input files are expected to be XML documents. They must follow the XSD available in `src/adql-validator/resources/queries.xsd`. All XML files currently present in the `src/adql/` directory are already following this XML schema.

This PR also includes 3 CI workflows:

1. **Validator test** _(file `test-validator.yml`)_: unitary tests for the ADQL validator itself. It aims to ensure the validator always behaves as expected.
2. **ADQL Validation** _(file `validate-queries.yml`)_: this action tests all queries of all XML files recursively found in `src/adql/`. The validation result is published in the Wiki of the repository. There is one report for the branch `master` and then one report for each opened Pull-Request. There is surely place for improvement when formatting this report ; this is a first proposal. _See [Example](https://github.com/gmantele/lyonetia/wiki)_.
3. **Remove obsolete report** _(file `remove-pr-report.yml`)_: removes from the Wiki the report associated with a closed Pull-Request. This is cleanup action aiming to avoid collecting useless reports in the Wiki.

The two first CI workflows run when opening a pull-request or pushing commits to the `master` branch. The last CI workflow runs only when a Pull-Request is closed.

In order to make a clear distinction between service dependent queries and IVOA standard queries, a new directory has been created in `src/adql`: `src/adql/ivoa/`. For the moment, it only contains one very simple XML file.

Anybody who wants to contribute to this ADQL validation project/repository is invited to append/update/delete queries in the `src/adql/` directory and more especially in the `src/adql/ivoa/` one ; later, it would perfectly be possible to limit the validation to only the latter in order to avoid noisy validation failures.

_**Warning:** note that currently the VOLLT library is not yet complete ; for instance, set operators and the `COALESCE` function are still missing. Besides, some failures might come from imperfections in the library code. All validation failures can then help improving this library in the same time as validating the ADQL language. So do not hesitate to report any mistake that seem to come from the library itself and should rather work in ADQL._

### CODE REVIEW

**Comment by jd-au** [comment]
It is great to see the validation in action. The reports look very useful. 

My only suggestion is to have an index of the reports at the top so one can a) see an overview and b) jump to specific reports of interest. This is inspired by the jenkins unit test reports (e.g. which have an overall success report and then a table of each package and the results of that package. Note that this is a future enhancement suggestion and I think this PR is good to go as is.

**Comment by gmantele** [comment]
Indeed, that was exactly what I had in mind when I said "there is a place for improvement" 😁

**Comment by msdemlei** [comment]
On Mon, Dec 20, 2021 at 10:06:28AM -0800, Grégory Mantelet wrote:
> This PR also includes 3 CI workflows:

Incidentally, in src/adql/gavo/testdachs.py there's a similar test
script that you should be able to simply run once you install the
python3-gavodachs2 package (assuming a bullseye Debian container).
There are a few failures still for what's in bullseye, though.  I can
explain :-).

I'm too lazy right now to wade through the diffs, but if the script
that runs in the end runs

python3 src/adql/gavo/testdachs.py <whereever-you-get-your-xmls-from>

that would also run the queries against DaCHS.  FWIW.

I'm of course not opposed at all to moving the script somewhere more
appropriate.

**Comment by jd-au** [comment]
Unless there are objections I'll merge this tomorrow.

**Pull request merged**
