### PR TITLE
PEG version of ADQL 2.1

### PR DESCRIPTION
**Pull request by jontxu**
@msdemlei and I have worked on making a machine-readable grammar, and for that we thought of writing it on PEG. It supports the 2.1 version, with some changes like terminals not being rules and removing some superflous identifiers.

The downside is that we depend on [Arpeggio](https://github.com/textX/Arpeggio) for this, which uses a slightly different syntax.

Some examples which had incorrect XML and lacked descriptions have also been fixed.

### CODE REVIEW

**Comment by gmantele** [comment]
I have not looked at this Pull Request yet, but seeing the following sentence immediately raised my attention. _So, maybe my comment is not appropriate ; if so, just tell me._

> The downside is that we depend on [Arpeggio](https://github.com/textX/Arpeggio) for this, which uses a slightly different syntax.

Is this PEG grammar only for your implementation or is it also for the IVOA Definition of ADQL 2.1?

If it is for you, ok: why not using a special syntax.
But if the goal is to write a PEG grammar for the official grammar of ADQL-2.1, I do not agree.

That's what was already done for the actual BNF of ADQL-2.0 (it is a special BNF syntax that is defined nowhere else). I would rather prefer having a proper syntax of PEG grammar that could be used by anybody who wants to implement a parser in his/her preferred language. Otherwise, it would mean that everybody must use Python+Arpeggio....or else one would have to to alter the official ADQL's PEG grammar to make it work with a different language. I did that for ADQL-2.0 and its BNF, and it was kind of a headache. I would appreciate not having to do so with a PEG grammar....that was actually the whole point of using this grammar syntax. If everybody uses exactly the same grammar, there are less chance of having broken parsers.

If the syntax is slightly different, why using Arpeggio?

Is there no other PEG parser in Python based on standard PEG syntax? I am not all an expert in Python , but can not [pyPEG](https://fdik.org/pyPEG/) be a valid alternative for instance?

**Comment by jontxu** [comment]
Don't worry. It's not inappropiate and I understand your concern.

>Is this PEG grammar only for your implementation or is it also for the IVOA Definition of ADQL 2.1?

It *is* supposed to be the IVOA definition of ADQL 2.1.

>If it is for you, ok: why not using a special syntax.
>But if the goal is to write a PEG grammar for the official grammar of ADQL-2.1, I do not agree.

The syntax between Arpeggio-PEG and actual PEG differ in three things:
1. Comments start with `//` instead of `#`
2. Rules end up with `;`
3. There is some `#{}` class thing which we haven't used.

Check [the official paper](http://bford.info/pub/lang/peg.pdf) or the [Rattler documentation](https://relishapp.com/jarhart/rattler/docs/peg-syntax) (a tool written in Ruby, apparently).

If you check https://github.com/ivoa/lyonetia/pull/11/commits/9d1adb737e70117ad2a38223ac2dd216fcd6c54a you can see there are two files, one with the actual PEG syntax and the other one with the Arpeggio one.

>That's what was already done for the actual BNF of ADQL-2.0 (it is a special BNF syntax that is defined nowhere else). I would rather prefer having a proper syntax of PEG grammar that could be used by anybody who wants to implement a parser in his/her preferred language. Otherwise, it would mean that everybody must use Python+Arpeggio....or else one would have to to alter the official ADQL's PEG grammar to make it work with a different language. I did that for ADQL-2.0 and its BNF, and it was kind of a headache. I would appreciate not having to do so with a PEG grammar....that was actually the whole point of using this grammar syntax. If everybody uses exactly the same grammar, there are less chance of having broken parsers.

@msdemlei and I actually talked a lot about this issue. We wanted to write an implementation agnostic grammar. The only thing that would make it Arpeggio dependant would be 1) the syntax and 2) patching Arpeggio for longest match support (which hasn't been done).

We used Arpeggio to test the PEG grammar we wrote with the queries present on `adql/gavo` and `adql/roe`. It's not that we used a tool like JavaCC or something like that. Arpeggio reads (and parses) the PEG file, making the according tree; and we just feed it our queries.

**Comment by Zarquan** [comment]
Hi all,

@jontxu This looks like a really useful contribution to ADQL, and I look forward to working with you on developing this further. However, there is a minor issue we need to clarify with regard to version numbers.

The published timeline and plans for the next versions of ADQL are to complete ADQL-2.1 as soon as possible, with minimal changes to the text and BNF grammar, and then to move to a machine readable PEG grammar in the 3.x series.

Replacing the human readable BNF grammar with a machine readable PEG grammar represents a significant change to the way that specification is defined and so the plan is to implement this as a major version step, 2.x to 3.x.

Looking forward, beyond the 2.x series; the first step in developing the ADQL-3.x series will be to create a PEG grammar that implements the same functionality as the final version of the ADQL-2.x series. Which means if you change the name of the PEG file from `adql2.1.peg` to `adql-3.0.peg`, then this contribution has a good chance of becoming the basis for the grammar definition for ADQL-3.0.

Thanks,
-- Dave

**Comment by Zarquan** [comment]
> The syntax between Arpeggio-PEG and actual PEG differ in three things:
> 
> 1. Comments start with `//` instead of `#`
> 2. Rules end with `;`
> 3. There is some `#{}` class thing which we haven't used.
> .... 
> If you check [9d1adb7](https://github.com/ivoa/lyonetia/commit/9d1adb737e70117ad2a38223ac2dd216fcd6c54a) you can see there are two files, one with the actual PEG syntax and the other one with the Arpeggio one.
> 

If the only differences between the two are minor syntax changes, then to avoid confusion, could you remove the Arpeggio version and replace it with a shell script that uses something like `sed` or `awk` to generate the Arpeggio version from the vanilla PEG version ?

**Comment by jontxu** [comment]
Hi,

@Zarquan no problems from my end. I don't know if @msdemlei has any input on this but I see reasonable making this the boilerplate for the 3.x series. As for the `sed` thing, I actually had in mind doing the opposite (since it might a priory seem simpler) but I've got no qualms on doing it.

We will try to add the change as soon as possible.

**Comment by msdemlei** [comment]
Hi,

On Sun, Feb 10, 2019 at 07:11:05AM -0800, Zarquan wrote:
> The published timeline and plans for the next versions of ADQL are
> to complete ADQL-2.1 as soon as possible, with minimal changes to
> the text and BNF grammar, and then to move to a machine readable
> PEG grammar in the 3.x series.

I've never been a big fan of committing to a major version step when
what we intend to do is indeed keep backwards compatibility in the
language (i.e., the set of syntactically correct strings).  Changing
the specification *technique* while not introducing incompatible
changes in the *content* does not, I'd argue, call for a major
version step with all the interoperability woes that brings with it.

> implements the same functionality as the final version of the
> ADQL-2.x series. Which means if you change the name of the PEG file
> from `adql2.1.peg` to `adql-3.0.peg`, then this contribution has a
> good chance of becoming the basis for the grammar definition for
> ADQL-3.0.

Well, what it currently does  is describe 2.1 (including the
still-broken rules for the bitwise logical operations).  So, I'd say
let's either elide the version number or keep it at 2.1.  A new
version signature, be it 2.2 or 3.0, can be chosen if we really
introduce new features (or start rejecting legacy constructs).

          -- Markus

**Comment by jontxu** [comment]
Hi all,

I just wrote and committed a small script which converts the standard PEG syntax to a working Arpeggio syntax. I had to update the file a bit because inline comments didn't work well for the time being.

Since we have also got the `debug.py` file I thought that it should be in its own file. You can test it by running `python convert.py` and then `python testpeg.py`

**Comment by jontxu** [comment]
Any news, @Zarquan? I think it's the PR is ready for merging.

**Pull request merged**
